// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TE0dKtOiqC5kLU3H1mdkEdr0sEZ2v2U',
    appId: '1:111798436989:web:e8518529d2fec2864d9d14',
    messagingSenderId: '111798436989',
    projectId: 'edupay-app-96f88',
    authDomain: 'edupay-app-96f88.firebaseapp.com',
    storageBucket: 'edupay-app-96f88.firebasestorage.app',
    measurementId: 'G-8HJFN1RDY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAaJKpMp8k4ET8s2IHwEbjOE1ub-HOkw',
    appId: '1:111798436989:android:2a79b6425e71ea164d9d14',
    messagingSenderId: '111798436989',
    projectId: 'edupay-app-96f88',
    storageBucket: 'edupay-app-96f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2G-CmRQPrzHLoSGKtPSfZHwjDT8pZzAs',
    appId: '1:111798436989:ios:adf8a1ee97a81e024d9d14',
    messagingSenderId: '111798436989',
    projectId: 'edupay-app-96f88',
    storageBucket: 'edupay-app-96f88.firebasestorage.app',
    iosBundleId: 'com.example.studentExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2G-CmRQPrzHLoSGKtPSfZHwjDT8pZzAs',
    appId: '1:111798436989:ios:adf8a1ee97a81e024d9d14',
    messagingSenderId: '111798436989',
    projectId: 'edupay-app-96f88',
    storageBucket: 'edupay-app-96f88.firebasestorage.app',
    iosBundleId: 'com.example.studentExpenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1TE0dKtOiqC5kLU3H1mdkEdr0sEZ2v2U',
    appId: '1:111798436989:web:850e1e79defe852c4d9d14',
    messagingSenderId: '111798436989',
    projectId: 'edupay-app-96f88',
    authDomain: 'edupay-app-96f88.firebaseapp.com',
    storageBucket: 'edupay-app-96f88.firebasestorage.app',
    measurementId: 'G-BJQL1YST80',
  );
}
